services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/back/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
  nodejs:
    build: ./back
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./back:/usr/src/app