version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    env_file:
      - .env
    ports:
        - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
