name: Backend Test and Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_test_and_deploy:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run tests
        run: |
          cd back
          npm ci
          npm run test -- --forceExit

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Env Variables
        run: |
          cd back
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifact
        run: |
          cd back
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          cd back
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --prod

      - name: Build Docker Image
        run: |
          cd docker
          docker compose build

      - name: Start Docker Compose
        run: |
          cd docker
          docker compose up -d

      - name: Verify Running Containers
        run: docker ps

  trigger_event:
    runs-on: ubuntu-latest
    needs: build_test_and_deploy
    steps:
      - name: Fire event
        run: |
          curl -L\
            -X POST\
            -H "Accept: application/vnd.github+json"\
            -H "Authorization: Bearer ${{ secrets.PERSONNAL_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/repos/${{ github.repository }}/dispatches\
            -d '{"event_type": "test_frontend"}'
