name: Frontend Build & Deploy

on:
  repository_dispatch:
    types: [ deploy_frontend ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies, build and test
        run: |
          cd front
          npm ci
          npm run build --if-present --configuration=production
          npm test

      - name: Build Docker Image and Start Container
        run: |
          cd docker
          docker compose -f docker-compose-frontend.yml build
          docker compose -f docker-compose-frontend.yml up -d         

      - name: Verify Running Containers
        run: docker ps

      - name: Set up GitHub Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: front/dist/ynov-ci-groupe/browser

  deploy:
    needs: [ build_test ]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy frontend to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: front/dist/ynov-ci-groupe/browser

      - name: Deploy docs to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: front/docs
          prefix: docs
