name: Frontend Tests

on:
  repository_dispatch:
    types: [ test_frontend ]

jobs:
  test:
    name: Run frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          cd front
          npm ci

      - name: Build in production mode
        run: |
          cd front
          npm run build --if-present --configuration=production

      - name: Run Jest unit tests
        run: |
          cd front
          npx jest --coverage

      - name: Verify Cypress installation
        run: |
          cd front
          npx cypress verify

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: front
          start: "npm start"
          wait-on: "http://localhost:4200"
          browser: chrome
          headless: true

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  trigger_event:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Fire event
        run: |
          curl -L\
            -X POST\
            -H "Accept: application/vnd.github+json"\
            -H "Authorization: Bearer ${{ secrets.PERSONNAL_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/repos/${{ github.repository }}/dispatches\
            -d '{"event_type": "deploy_frontend"}'